# Generated by Django 5.2 on 2025-05-26 14:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tripimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
