# Generated by Django 5.2 on 2025-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tripimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='url',
            field=models.URLField(default='www.url.com'),
            preserve_default=False,
        ),
    ]
