# Generated by Django 5.2.1 on 2025-05-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trip_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
