# Generated by Django 5.2.1 on 2025-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trip_destination_priority_trip_trip_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_priority',
            field=models.BooleanField(default=False),
        ),
    ]
