# Generated by Django 5.2.1 on 2025-05-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_trip_destination_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='group_priority',
            field=models.BooleanField(default=False),
        ),
    ]
